name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: '^1.18.4'
        run: go version

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: make test
